site_name: Bazarr Documentation / Wiki
site_description: Documentation for Bazarr, Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
site_author: TRaSH
site_url: https://docs.bazarr.media

repo_url: https://github.com/TRaSH-/bazarr-docs
repo_name: TRaSH-/bazarr-docs

copyright: Copyright &copy; 2021 Bazarr

extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/discord
      link: https://docs.bazarr.media/discord
    - icon: fontawesome/brands/github-square
      link: https://github.com/morpheus65535/bazarr

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - lightgallery

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false
  - awesome-pages
#  - macros:
#      j2_block_start_string: "[[%"
#      j2_block_end_string: "%]]"
#      j2_variable_start_string: "[["
#      j2_variable_end_string: "]]"
  - redirects:
      redirect_maps:
        discord.md: https://discord.gg/MH2e2eb
#        Radarr/V3/How-to-importexport-Custom-Formats-and-truly-make-use-of-it.md: Radarr/V3/Radarr-import-custom-formats.md
#        Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md: Radarr/V3/Radarr-collection-of-custom-formats.md
#        Sonarr/V3/Remote-Path-Mappings-explained-for-Sonarr.md: Sonarr/V3/Sonarr-remote-path-mapping.md
#        Misc/Discord-Notifier-Basic-Setup.md: Notifiarr/Quick-Start.md
#        Misc/Discord-Notifiarr-Setup.md: Notifiarr/Quick-Start.md
#        hardlinks.md: Misc/how-to-set-up-hardlinks-and-atomic-moves.md
#        hardlink.md: Misc/how-to-set-up-hardlinks-and-atomic-moves.md
#        custom-formats.md: Radarr/V3/Radarr-collection-of-custom-formats.md
#        cf.md: Radarr/V3/Radarr-collection-of-custom-formats.md
#        TorGuard.md: Misc/how-to-set-up-hardlinks-and-atomic-moves.md
#        torguard.md: Misc/how-to-set-up-hardlinks-and-atomic-moves.md
#        compose.md: Misc/how-to-provide-a-docker-compose.md
#        Golden-Rule.md: Misc/x265-4k.md
#        show-unknown.md: Radarr/V3/Tips/Radarr-show-unknown-movie-items.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
#    - navigation.tabs
#    - navigation.expand
  language: en
  palette:
    primary: indigo
    accent: indigo
    scheme: default
  font:
    text: "Roboto"
    code: "Fira Code"
  favicon: img/favicon.png
  logo: img/logo.png
